### ISSUE TITLE
Patched .gdi will not start

### ISSUE THREAD

**Issue by microace** [DerekPascarella/RainbowCotton-EnglishPatchDreamcast#1]
Applied patch on the  Redump bin/cue dump. The resulting .gdi will not start.

I tested with the latest versions of redream and flycast emulator. I do not have a real dreamcast with an ODE to test with.

**Comment by DerekPascarella** [comment]
Try enabling HLE BIOS in your emulator. My patches are all designed to work on real hardware, but so far I’ve been able to use RetroArch+Flycast for testing, no issues booting there.

**Comment by microace** [comment]
It works with HLE in both emulators, thanks.

**Comment by DerekPascarella** [comment]
You're welcome!  Enjoy.
